# Generated by Django 5.2.8 on 2025-11-26 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        blank=True, help_text="User ID (nullable for now)", null=True
                    ),
                ),
                (
                    "linkedin_url",
                    models.TextField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                ("name", models.TextField(help_text="Profile name")),
                (
                    "headline",
                    models.TextField(
                        blank=True, help_text="Professional headline", null=True
                    ),
                ),
                (
                    "disc_primary",
                    models.TextField(
                        blank=True, help_text="Primary DISC type", null=True
                    ),
                ),
                (
                    "disc_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="DISC breakdown (dominance, influence, steadiness, compliance)",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full analysis response from Gemini",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
