# Generated by Django 5.2.8 on 2025-11-30 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzedProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        blank=True, help_text="User ID (nullable for now)", null=True
                    ),
                ),
                ("name", models.TextField(help_text="Profile name")),
                (
                    "headline",
                    models.TextField(
                        blank=True, help_text="Professional headline", null=True
                    ),
                ),
                (
                    "linkedin_profile",
                    models.TextField(
                        blank=True, help_text="LinkedIn profile URL", null=True
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True, help_text="Confidence score (0-100)", null=True
                    ),
                ),
                (
                    "dominance",
                    models.IntegerField(
                        blank=True, help_text="Dominance score (0-100)", null=True
                    ),
                ),
                (
                    "influence",
                    models.IntegerField(
                        blank=True, help_text="Influence score (0-100)", null=True
                    ),
                ),
                (
                    "steadiness",
                    models.IntegerField(
                        blank=True, help_text="Steadiness score (0-100)", null=True
                    ),
                ),
                (
                    "compliance",
                    models.IntegerField(
                        blank=True, help_text="Compliance score (0-100)", null=True
                    ),
                ),
                (
                    "disc_primary",
                    models.TextField(
                        blank=True, help_text="Primary DISC type", null=True
                    ),
                ),
                (
                    "key_insights",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Key insights as list of strings",
                    ),
                ),
                (
                    "pain_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Pain points as list of strings",
                    ),
                ),
                (
                    "communication_style",
                    models.TextField(
                        blank=True,
                        help_text="Communication style description",
                        null=True,
                    ),
                ),
                (
                    "sales_approach",
                    models.TextField(
                        blank=True, help_text="Sales approach description", null=True
                    ),
                ),
                (
                    "best_approach",
                    models.TextField(
                        blank=True, help_text="Best approach description", null=True
                    ),
                ),
                (
                    "ideal_pitch",
                    models.TextField(
                        blank=True, help_text="Ideal pitch description", null=True
                    ),
                ),
                (
                    "communication_dos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Communication do's as list of strings",
                    ),
                ),
                (
                    "communication_donts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Communication don'ts as list of strings",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full analysis response from Gemini",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyzed Profile",
                "verbose_name_plural": "Analyzed Profiles",
                "db_table": "analyzed_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
