# Generated by Django 5.2.8 on 2025-12-13 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_analyzedprofile_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="LinkedIn profile ID (e.g., sumit-patil-1b31a9271)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "linkedin_profile",
                    models.TextField(
                        blank=True, help_text="Full LinkedIn profile URL", null=True
                    ),
                ),
                ("name", models.TextField(help_text="Profile name")),
                (
                    "headline",
                    models.TextField(
                        blank=True, help_text="Professional headline", null=True
                    ),
                ),
                (
                    "location",
                    models.TextField(blank=True, help_text="Location", null=True),
                ),
                (
                    "about",
                    models.TextField(blank=True, help_text="About section", null=True),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, help_text="Experience section", null=True
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Education section", null=True
                    ),
                ),
                ("skills", models.TextField(blank=True, help_text="Skills", null=True)),
                (
                    "connections_count",
                    models.CharField(
                        blank=True,
                        help_text="Connections count",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "followers_count",
                    models.CharField(
                        blank=True,
                        help_text="Followers count",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "current_company",
                    models.TextField(
                        blank=True, help_text="Current company", null=True
                    ),
                ),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="Highlights", null=True),
                ),
                (
                    "services",
                    models.TextField(blank=True, help_text="Services", null=True),
                ),
                (
                    "licenses_and_certifications",
                    models.TextField(
                        blank=True, help_text="Licenses and certifications", null=True
                    ),
                ),
                (
                    "activity",
                    models.TextField(blank=True, help_text="Activity", null=True),
                ),
                (
                    "posts",
                    models.JSONField(
                        blank=True, default=list, help_text="Recent posts"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete raw scraped data as JSON",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Creation timestamp"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last update timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Data",
                "verbose_name_plural": "Raw Data",
                "db_table": "raw_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="analyzedprofile",
            name="profile_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="LinkedIn profile ID (e.g., sumit-patil-1b31a9271)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="analyzedprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AddField(
            model_name="analyzedprofile",
            name="raw_data_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to raw scraped data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyzed_profiles",
                to="api.rawdata",
            ),
        ),
    ]
