# Generated by Django 5.2.8 on 2025-12-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rawdata_analyzedprofile_profile_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdata",
            name="licenses_and_certifications",
        ),
        migrations.AddField(
            model_name="rawdata",
            name="top_skills",
            field=models.TextField(blank=True, help_text="Top skills", null=True),
        ),
    ]
