# Generated by Django 5.2.8 on 2025-12-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_rawdata_licenses_and_certifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawdata",
            name="followers_count",
        ),
        migrations.RemoveField(
            model_name="rawdata",
            name="highlights",
        ),
        migrations.RemoveField(
            model_name="rawdata",
            name="services",
        ),
    ]
